project:
  type: website
  output-dir: docs

website:
  title: "Kayla Esser"
  favicon: images/strawberry.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research publications
      - href: presentations.qmd
        text: Presentations
      - href: experience.qmd
        text: Experience
      - href: funding.qmd
        text: Funding
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
