---
title: "Presentations"
---

## Research posters (selected)

Cheung T, **Esser K**, Cost K, Korczak D, Anagnostou E, Birken C, Charach A, Monga S, Crosbie J. Comparison of Data Substitution Methods for Missing Data in a Longitudinal Study. *Canadian Psychological Association Annual Convention*. Toronto, Canada. Jun 23-25, 2023.

Bruno N, **Esser K**, Rose J, Fayed N, Wittenberg J, Saunders N, Szatmari P, Wright E, Vigod S, Cohen E, Orkin J. Integrated Psychiatric Support for Caregivers of Children with Medical Complexity. *Canadian Health and Wellbeing in Developmental Disabilities Conference*. Toronto, Canada. Feb 8-9, 2023.

Hassan D, **Esser K**, Orkin J, Oberlander T, Siden H, Cohen E, Diskin C. Management of Pain in Children with Severe Neurological Impairments within a Complex Care Program. *Pediatric Academic Societies 2022 Annual Conference*. Apr 21-25 2022, Denver, Colorado.

**Esser K**, Moore C, Hounsell KG, Davis A, Sunderji A, Shulman R, Cohen E, Orkin J. Housing Need Amongst Children with Medical Complexity: A Cross-Sectional Study of Three Populations. Poster presented virtually at: Canadian Paediatric Society Virtual Conference; 2021 Jun 23-25; Online (Canada).

**Esser K**, Cardenas A, Lee S, Orkin J. Transition to Adult primary care for youth with medical Complexity through the use of Telemedicine (TACT): a feasibility study. Poster presented virtually at: Canadian Transitions to Adulthood Conference. Children's Healthcare Canada; 2021 Jan 26-27; Online (Canada).

**Esser K**, Parmar A, Major N, Church P, Cohen E, Orkin J. Coach, Coordinated, Enhanced Neonatal Transition: intervention development for nurse-delivered Acceptance and Commitment Therapy. Poster presented at: Precision and Personalization in Child and Youth Mental Health. Research Psychiatry Day; 2020 Feb 7; Toronto, Canada.

## Talks

**Esser K**, Moore C, and Orkin J. "Housing Need Amongst Children with Medical Complexity: A Cross-Sectional Descriptive Study of Three Populations" at Endocrine Research Team Meeting, The Hospital for Sick Children, 12 January 2021.

**Esser K**, and Colapinto K. "Introducing Acceptance and Commitment Therapy in the NICU" at Mindfulness and Compassion Rounds, The Hospital for Sick Children, 4 August 2020.
