---
title: "Research Publications"
---

Teicher J, Moore C, **Esser K**, et al. (2022). <a href="https://journals.sagepub.com/doi/10.1177/00099228221142102"> The Experience of Parental Caregiving for Children with Medical Complexity. </a> *Clinical Pediatrics*.

**Esser K**, Davis P, Badour B, et al. (2022). <a href="https://www.longwoods.com/content/27017/healthcare-quarterly/one-system-multiple-hospitals-a-unified-paediatric-healthcare-system-response-to-the-covid-19-pand"> One system, multiple hospitals: A unified paediatric healthcare system response to COVID-19. </a> *Healthcare Quarterly*.

Cardenas A, **Esser K**, Wright E, et al. (2022). <a href="https://www.sciencedirect.com/science/article/pii/S1876285922002911"> Caring for the Caregiver (C4C): An Integrated Stepped Care Model for Caregivers of Children With Medical Complexity. </a>  *Acad Pediatr*.

**Esser K**, Moore C, Hounsell KG, et al. (2021). <a href="https://www.sciencedirect.com/science/article/pii/S1876285921004599"> Housing Need Among Children with Medical Complexity: A Cross-Sectional Descriptive Study of Three Populations. </a>  *Acad Pediatr*.

Parmar A, **Esser K**, Barreira L, et al. (2021). <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8345967/"> Acceptance and Commitment Therapy for Children with Special Health Care Needs and Their Parents: A Systematic Review and Meta-Analysis. </a> *Int J Environ Res Public Health*.

Orkin J, Major N, **Esser K**, et al. (2021). <a href="https://bmjopen.bmj.com/content/11/7/e046706.long"> Coached, Coordinated, Enhanced Neonatal Transition (CCENT): Protocol for a multicentre pragmatic randomized controlled trial of transition-to-home support for parents of high-risk infants. </a>  *BMJ Open*.

Hounsell KG, Moore C, Zahavi A, **et al.** (2021). <a href="https://publications.aap.org/pediatrics/article/148/1/e2020018937/179944/The-Experience-of-Housing-Needs-Among-Families"> The experience of housing needs among families caring for children with medical complexity. </a>  *Pediatrics*.

**Esser K**, Barreira L, Miller D, et al. (2020). <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7850279/"> Exploring Acceptance and Commitment Therapy for parents of preterm infants. </a> *Paediatrics & Child Health*.
